### ISSUE TITLE
Senate tweets

### ISSUE THREAD

**Issue by josuetsm** [keyonvafa/tbip#9]
Hi Keyon,

Thank you very much again for the well-documented repository. I've tried to reproduce the results of the paper, but I cannot find the voxgov_tweets.csv file on the website https://voxgov.com. Where can I find it?

**Comment by keyonvafa** [comment]
Hi Josue,

Thanks for the note. The Voxgov data was shared with us privately and so unfortunately we're unable to release it. One option is to use another scraped datasets of tweets, e.g. [this Reddit post](https://www.reddit.com/r/datasets/comments/6fniik/over_one_million_tweets_collected_from_us/) contains a scraped dataset of U.S. Senate tweets.

**Comment by josuetsm** [comment]
Thanks for the quick answer, I'll try with that dataset.
